fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"

  symlinks:
    profile_base: "#{source_dir}"
